apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
    version: {{ .Values.service.labels.version }}
spec:
  selector:
    app: {{ .Values.service.selector.app }}
    version: {{ .Values.service.selector.version }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
