apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue-green-poc
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-poc
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-poc
        version: blue
    spec:
      containers:
      - name: my-webserver
        image: stevendeke/bluegreen:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
  namespace: blue-green
  labels:
    app: blue-green-poc
    version: blue
spec:
  selector:
    app: blue-green-poc
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
