apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: blue-green
  labels:
    app: blue-green-poc
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-poc
      version: blue 
  template:
    metadata:
      labels:
        app: blue-green-poc
        version: blue
    spec:
      containers:
      - name: my-webserver
        image: stevendeke/bluegreen:1.0.0
        ports:
        - containerPort: 80


