apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: blue-green-poc
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-poc
      version: green
  template:
    metadata:
      labels:
        app: blue-green-poc
        version: green
    spec:
      containers:
      - name: my-webserver
        image: stevendeke/bluegreen:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: blue-green
  labels:
    app: blue-green-poc
    version: green
spec:
  selector:
    app: blue-green-poc
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  type: NodePort
