apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: blue-green
  labels:
    app: blue-green-poc
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-poc
      version: green
  template:
    metadata:
      labels:
        app: blue-green-poc
        version: green
    spec:
      containers:
      - name: my-webserver
        image: stevendeke/bluegreen:1.0.1
        ports:
        - containerPort: 80
